matchbox-flatcar: wipe additional disks
Exposes a variable to the user for wiping any additional disks attached
to the machine. Default is false.

When set to true, any additional disks attached to the hardware are
wiped clean before proceeding with the Flatcar Container Linux
installation.

The reason this is being done is to provide clean and unformatted disk
devices to the Lokomotive components [openebs and rook] for storage
orchestration.

Both rook and openebs fail to use the disks that have data or filesystem
already present on the disk. This leads to among other issues, failed
installation where PVCs get stuck in pending state.

Signed-off-by: Imran Pochi <imran@kinvolk.io>

diff --git a/assets/terraform-modules/matchbox-flatcar/templates/install.yaml.tmpl b/assets/terraform-modules/matchbox-flatcar/templates/install.yaml.tmpl
--- a/assets/terraform-modules/matchbox-flatcar/templates/install.yaml.tmpl
+++ b/assets/terraform-modules/matchbox-flatcar/templates/install.yaml.tmpl
@@ -36,6 +36,19 @@ storage:
           # unmount any leftovers at the beginning before we modify the disk the mount uses
           umount /tmp/oemfs || true
           lvchange -an /dev/mapper/* || true
+          %{~ if wipe_additional_disks ~}
+          disks="$(lsblk -lnpdb -x SIZE -o NAME \
+            | (
+            while IFS= read -r drive; do
+              mountpoints=$(lsblk -ln -o MOUNTPOINT "$drive")
+              if [[ -z "$mountpoints" ]]; then
+                echo "$drive"
+              fi
+            done))"
+          for disk in $${disks}; do
+            wipefs -f -a "$${disk}" || echo "error: failed to wipe $${disk}"
+          done
+          %{~ endif ~}
           curl --retry 10 "${ignition_endpoint}?{{.request.raw_query}}&os=installed" -o ignition.json
           flatcar-install \
             %{~ if install_to_smallest_disk ~}
